// Generated by CoffeeScript 1.6.3
(function() {
  var $, Http, Links;

  Http = require('../Http');

  $ = null;

  Links = (function() {
    function Links(jQuery) {
      var historyApi;
      $ = jQuery;
      historyApi = false;
      $(document).on('click', 'a.ajax:not(.not-ajax)', function(e) {
        var a, link;
        e.preventDefault();
        a = e.target.nodeName.toLowerCase() === 'a' ? $(e.target) : $(e.target).closest('a');
        link = a.attr('href');
        if (historyApi) {
          window.history.pushState({}, null, link);
        }
        return Http.get(link);
      });
    }

    return Links;

  })();

  module.exports = Links;

}).call(this);
