// Generated by CoffeeScript 1.7.1
(function() {
  var $, Links;

  $ = null;

  Links = (function() {
    Links.prototype.http = null;

    function Links(jQuery) {
      var historyApi;
      $ = jQuery;
      historyApi = false;
      $(document).on('click', 'a.ajax:not(.not-ajax)', (function(_this) {
        return function(e) {
          var a, link;
          e.preventDefault();
          a = e.target.nodeName.toLowerCase() === 'a' ? $(e.target) : $(e.target).closest('a');
          link = a.attr('href');
          if (historyApi) {
            window.history.pushState({}, null, link);
          }
          if (_this.http === null) {
            throw new Error('Please add Links extension into http object with addExtension method.');
          }
          return _this.http.get(link);
        };
      })(this));
    }

    return Links;

  })();

  module.exports = Links;

}).call(this);
