// Generated by CoffeeScript 1.6.3
(function() {
  var Http, Links, e, jquery;

  Http = require('../Http');

  try {
    jquery = require('jquery');
  } catch (_error) {
    e = _error;
    jquery = window.jQuery;
  }

  Links = (function() {
    function Links() {
      var historyApi;
      historyApi = false;
      jquery(document).on('click', 'a.ajax:not(.not-ajax)', function(e) {
        var a, link;
        e.preventDefault();
        a = e.target.nodeName.toLowerCase() === 'a' ? jquery(e.target) : jquery(e.target).closest('a');
        link = a.attr('href');
        if (historyApi) {
          window.history.pushState({}, null, link);
        }
        return Http.get(link);
      });
    }

    return Links;

  })();

  module.exports = Links;

}).call(this);
