// Generated by CoffeeScript 1.7.1
(function() {
  var Loading,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Loading = (function() {
    function Loading() {
      this.complete = __bind(this.complete, this);
      this.send = __bind(this.send, this);
    }

    Loading.prototype.send = function(response, request) {
      return document.body.style.cursor = 'progress';
    };

    Loading.prototype.complete = function(response, request) {
      return document.body.style.cursor = 'auto';
    };

    return Loading;

  })();

  module.exports = Loading;

}).call(this);
