// Generated by CoffeeScript 1.6.3
(function() {
  var Http, Loading,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Http = require('../Http');

  Loading = (function() {
    function Loading() {
      this.onComplete = __bind(this.onComplete, this);
      this.onSend = __bind(this.onSend, this);
      Http.addExtension('loading', {
        send: this.onSend,
        complete: this.onComplete
      });
    }

    Loading.prototype.onSend = function(response, request) {
      return document.body.style.cursor = 'progress';
    };

    Loading.prototype.onComplete = function(response, request) {
      return document.body.style.cursor = 'auto';
    };

    return Loading;

  })();

  module.exports = Loading;

}).call(this);
