// Generated by CoffeeScript 1.7.1
(function() {
  var Offline;

  Offline = (function() {
    Offline.prototype.timer = null;

    Offline.prototype.offline = false;

    function Offline(url, timeout) {
      if (url == null) {
        url = 'favicon.ico';
      }
      if (timeout == null) {
        timeout = 5000;
      }
      this.start(url, timeout);
    }

    Offline.prototype.start = function(url, timeout) {
      if (url == null) {
        url = 'favicon.ico';
      }
      if (timeout == null) {
        timeout = 5000;
      }
      return this.timer = window.setInterval((function(_this) {
        return function() {
          return _this.http.get(url, {
            data: {
              r: Math.floor(Math.random() * 1000000000)
            }
          }).then(function(response) {
            if ((response.status >= 200 && response.status <= 300) || response.status === 304) {
              if (_this.offline) {
                _this.offline = false;
                return _this.http.emit('connected');
              }
            } else if (!_this.offline) {
              _this.offline = false;
              return _this.http.emit('disconnected');
            }
          });
        };
      })(this), timeout);
    };

    Offline.prototype.stop = function() {
      if (this.timer !== null) {
        window.clearInterval(this.timer);
        this.timer = null;
      }
      return this;
    };

    return Offline;

  })();

  module.exports = Offline;

}).call(this);
