// Generated by CoffeeScript 1.6.3
(function() {
  var Http, Redirect;

  Http = require('../Http');

  Redirect = (function() {
    function Redirect() {
      Http.addExtension('redirect', {
        success: this.onSuccess
      });
    }

    Redirect.prototype.onSuccess = function(response, request) {
      if (typeof response.data.redirect !== 'undefined') {
        return window.location.href = response.data.redirect;
      }
    };

    return Redirect;

  })();

  module.exports = Redirect;

}).call(this);
