// Generated by CoffeeScript 1.7.1
(function() {
  var Redirect;

  Redirect = (function() {
    function Redirect() {}

    Redirect.prototype.success = function(response, request) {
      if (typeof response.data.redirect !== 'undefined') {
        return window.location.href = response.data.redirect;
      }
    };

    return Redirect;

  })();

  module.exports = Redirect;

}).call(this);
