// Generated by CoffeeScript 1.6.3
(function() {
  var Http, Snippets, e, jquery,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Http = require('../Http');

  try {
    jquery = require('jquery');
  } catch (_error) {
    e = _error;
    jquery = window.jQuery;
  }

  Snippets = (function() {
    Snippets.prototype._onRefresh = null;

    function Snippets() {
      this.onSuccess = __bind(this.onSuccess, this);
      this._onRefresh = [];
      Http.addExtension('snippets', {
        success: this.onSuccess
      });
    }

    Snippets.prototype.onSuccess = function(response, request) {
      var html, id, _ref, _results;
      if (typeof response.data.snippets !== 'undefined') {
        _ref = response.data.snippets;
        _results = [];
        for (id in _ref) {
          html = _ref[id];
          _results.push(this.updateSnippet(id, html));
        }
        return _results;
      }
    };

    Snippets.prototype.updateSnippet = function(id, html) {
      var el, ev, _i, _len, _ref, _results;
      el = jquery("#" + id);
      el.html(html);
      _ref = this._onRefresh;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        ev = _ref[_i];
        _results.push(ev(el));
      }
      return _results;
    };

    Snippets.prototype.onRefresh = function(fn) {
      this._onRefresh.push(fn);
      return this;
    };

    return Snippets;

  })();

  module.exports = Snippets;

}).call(this);
