// Generated by CoffeeScript 1.6.3
(function() {
  var $, Http, Snippets,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Http = require('../Http');

  $ = null;

  Snippets = (function() {
    function Snippets(jQuery) {
      this.onSuccess = __bind(this.onSuccess, this);
      $ = jQuery;
      Http.addExtension('snippets', {
        success: this.onSuccess
      });
    }

    Snippets.prototype.onSuccess = function(response, request) {
      var html, id, _ref, _results;
      if (typeof response.data.snippets !== 'undefined') {
        _ref = response.data.snippets;
        _results = [];
        for (id in _ref) {
          html = _ref[id];
          _results.push(this.updateSnippet(id, html));
        }
        return _results;
      }
    };

    Snippets.prototype.updateSnippet = function(id, html) {
      var el;
      el = $("#" + id);
      return el.html(html);
    };

    return Snippets;

  })();

  module.exports = Snippets;

}).call(this);
