// Generated by CoffeeScript 1.7.1
(function() {
  var Snippets,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Snippets = (function() {
    function Snippets() {
      this.success = __bind(this.success, this);
    }

    Snippets.prototype.success = function(response, request) {
      var html, id, _ref, _results;
      if (typeof response.data.snippets !== 'undefined') {
        _ref = response.data.snippets;
        _results = [];
        for (id in _ref) {
          html = _ref[id];
          _results.push(this.updateSnippet(id, html));
        }
        return _results;
      }
    };

    Snippets.prototype.updateSnippet = function(id, html) {
      return document.getElementById(id).innerHTML = html;
    };

    return Snippets;

  })();

  module.exports = Snippets;

}).call(this);
