// Generated by CoffeeScript 1.6.3
(function() {
  var Queue;

  Queue = (function() {
    Queue.prototype.requests = null;

    Queue.prototype.running = false;

    function Queue() {
      this.requests = [];
    }

    Queue.prototype.add = function(request, fn) {
      return this.requests.push({
        request: request,
        fn: fn
      });
    };

    Queue.prototype.run = function() {
      var data;
      if (this.running === false && this.requests.length > 0) {
        this.running = true;
        data = this.requests.shift();
        return data.fn();
      }
    };

    Queue.prototype.next = function() {
      this.running = false;
      return this.run();
    };

    return Queue;

  })();

  module.exports = Queue;

}).call(this);
