// Generated by CoffeeScript 1.6.3
(function() {
  var EventEmitter, Request, Xhr,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Xhr = require('./Xhr');

  EventEmitter = require('events').EventEmitter;

  Request = (function(_super) {
    __extends(Request, _super);

    Request.prototype.url = null;

    Request.prototype.type = 'GET';

    Request.prototype.data = null;

    Request.prototype.jsonp = null;

    Request.prototype.xhr = null;

    Request.prototype.response = null;

    function Request(url, type, data, jsonp) {
      var _this = this;
      this.url = url;
      this.type = type != null ? type : 'GET';
      this.data = data != null ? data : null;
      this.jsonp = jsonp != null ? jsonp : false;
      Request.__super__.constructor.apply(this, arguments);
      this.xhr = new Xhr(this.url, this.type, this.data, this.jsonp);
      this.response = this.xhr.response;
      this.xhr.on('success', function() {
        _this.emit('success', _this.response, _this);
        return _this.emit('complete', _this.response, _this);
      });
      this.xhr.on('error', function(err) {
        _this.emit('error', err, _this.response, _this);
        return _this.emit('complete', _this.response, _this);
      });
    }

    Request.prototype.setHeader = function(name, value) {
      return this.xhr.setHeader(name, value);
    };

    Request.prototype.send = function() {
      return this.xhr.send();
    };

    Request.prototype.abort = function() {
      return this.xhr.abort();
    };

    Request.prototype.getHeaders = function() {
      return this.xhr.getHeaders();
    };

    Request.prototype.getHeader = function(name) {
      return this.xhr.getHeader(name);
    };

    Request.prototype.setHeader = function(name, value) {
      return this.xhr.setHeader(name, value);
    };

    Request.prototype.setMimeType = function(mime) {
      return this.xhr.setMimeType(mime);
    };

    return Request;

  })(EventEmitter);

  module.exports = Request;

}).call(this);
