// Generated by CoffeeScript 1.6.3
(function() {
  var Response;

  Response = (function() {
    function Response() {}

    Response.prototype.state = 0;

    Response.prototype.status = null;

    Response.prototype.statusText = null;

    Response.prototype.data = null;

    Response.prototype.xml = null;

    return Response;

  })();

  module.exports = Response;

}).call(this);
