// Generated by CoffeeScript 1.7.1
(function() {
  var OriginalRequest, Request, Xhr,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  OriginalRequest = require('../Request');

  Xhr = require('./Xhr');

  Request = (function(_super) {
    __extends(Request, _super);

    function Request() {
      return Request.__super__.constructor.apply(this, arguments);
    }

    Request.prototype.createXhr = function(url, type, data, jsonp, jsonPrefix) {
      return new Xhr(url, type, data, jsonp, jsonPrefix);
    };

    return Request;

  })(OriginalRequest);

  module.exports = Request;

}).call(this);
