// Generated by CoffeeScript 1.7.1
(function() {
  var OriginalXhr, Xhr, XmlHttpMocks,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  OriginalXhr = require('../Xhr');

  XmlHttpMocks = require('../../external/XmlHttpRequest');

  Xhr = (function(_super) {
    __extends(Xhr, _super);

    function Xhr() {
      return Xhr.__super__.constructor.apply(this, arguments);
    }

    Xhr.prototype.createXhr = function() {
      return new XmlHttpMocks;
    };

    Xhr.prototype.receive = function(status, data, timeout) {
      if (timeout == null) {
        timeout = null;
      }
      return this.xhr.receive(status, data, timeout);
    };

    Xhr.prototype.receiveError = function(err) {
      return this.xhr.err(err);
    };

    Xhr.prototype.setResponseHeader = function(name, value) {
      return this.xhr.setResponseHeader(name, value);
    };

    return Xhr;

  })(OriginalXhr);

  module.exports = Xhr;

}).call(this);
